
import Head from 'next/head'
import HeaderSection from '../components/HeaderSection/HeaderSection'

import styles from '../styles/Home.module.css'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Compare the weather </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
         <HeaderSection/>
        <div className={styles.grid}>




        </div>
      </main>
    </div>
  )
}

export default Home



